language: ruby
cache: bundler
branches:
  only:
    - master
    - stable
env:
  global:
    - HEADLESS=true
    - RAILS_DB_ADAPTER=mysql2
    - RAILS_DB_NAME=hitobito_test
    - RAILS_ENV=development
rvm:
  - 2.1.7
  - 2.2.3
  - 2.3.1
  - 2.4.0
matrix:
  allow_failures:
    - rvm: 2.1.7
    - rvm: 2.3.1
    - rvm: 2.4.0
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH

  - unset BUNDLE_GEMFILE # we bundle in different directories
  - cd .. && git clone https://github.com/hitobito/hitobito.git hitobito
  - cd hitobito && git checkout -f $([[ $TRAVIS_BRANCH = 'stable' ]] && echo 'stable' || echo 'master')
  - export HITOBITO_CORE_DIR=$PWD
  - cp -v Wagonfile.ci Wagonfile
  - rvm use $TRAVIS_RUBY_VERSION --fuzzy
  - gem install bundler --version 1.9.10
  - bundle install --path vendor/bundle
  - for d in ../hitobito_*; do cd $d && cp -v $HITOBITO_CORE_DIR/Gemfile.lock ./ && rvm use $TRAVIS_RUBY_VERSION --fuzzy && bundle install --path vendor/bundle; done
  - cd $HITOBITO_CORE_DIR && rvm use $TRAVIS_RUBY_VERSION --fuzzy
script:
  - bundle exec rake db:create ci:wagon --trace
